import type { Theme } from './types';

/** Ayu Mirage. Palette from https://github.com/dempfi/ayu (ayu-mirage.sublime-color-scheme). */
export const ayuMirage: Theme = {
	name: 'Ayu Mirage',
	ui: {
		bg: '#242936',
		panelBg: '#1f2430',
		barBg: '#1f2430',
		statusBg: '#ffcc66',
		statusFg: '#242936',
		text: '#cccac2',
		dim: '#707a8c',
		faint: '#6e7c8f',
		accent: '#ffcc66',
		activeTabFg: '#cccac2',
		inactiveTabFg: '#707a8c',
		treeSelectedBg: '#2d3444',
		treeFocusBg: '#1a1f29',
		dirty: '#ffcc66',
		error: '#ff6666',
		folder: '#cccac2',
		cursor: '#ffcc66',
		scrollbar: '#707a8c',
		gutter: '#707a8c',
		currentLine: '#1a1f29',
		indentGuide: '#303848',
		gitAdded: '#87d96c',
		gitModified: '#80bfff',
		gitDeleted: '#f27983',
	},
	syntax: {
		comment: { fg: '#6e7c8f', italic: true },
		keyword: { fg: '#ffa659' },
		string: { fg: '#d5ff80' },
		number: { fg: '#dfbfff' },
		boolean: { fg: '#dfbfff' },
		constant: { fg: '#dfbfff' },
		function: { fg: '#ffd173' },
		type: { fg: '#73d0ff' },
		variable: { fg: '#cccac2' },
		property: { fg: '#f28779' },
		tag: { fg: '#5ccfe6' },
		operator: { fg: '#f29e74' },
		punctuation: { fg: '#cccac2' },
		label: { fg: '#ffdfb3' },
		escape: { fg: '#95e6cb' },
		embedded: { fg: '#cccac2' },
		error: { fg: '#ff6666' },
		'markup.heading': { fg: '#d5ff80', bold: true },
		'markup.strong': { fg: '#f28779', bold: true },
		'markup.italic': { fg: '#f28779', italic: true },
		'markup.raw': { fg: '#f29e74' },
		'markup.link': { fg: '#73d0ff' },
		'markup.link.url': { fg: '#73d0ff', underline: true },
		'markup.list': { fg: '#ffd173' },
		'markup.quote': { fg: '#95e6cb', italic: true },
	},
};
