import type { Theme } from './types';

/** Ayu Light. Palette from https://github.com/dempfi/ayu (ayu-light.sublime-color-scheme). */
export const ayuLight: Theme = {
	name: 'Ayu Light',
	ui: {
		bg: '#fcfcfc',
		panelBg: '#f8f9fa',
		barBg: '#f0f1f2',
		statusBg: '#ffaa33',
		statusFg: '#fcfcfc',
		text: '#5c6166',
		dim: '#828e9f',
		faint: '#adaeb1',
		accent: '#ffaa33',
		activeTabFg: '#5c6166',
		inactiveTabFg: '#828e9f',
		treeSelectedBg: '#e8ecf0',
		treeFocusBg: '#f0f1f2',
		dirty: '#ffaa33',
		error: '#e65050',
		folder: '#5c6166',
		cursor: '#ffaa33',
		scrollbar: '#828e9f',
		gutter: '#828e9f',
		currentLine: '#f0f1f2',
		indentGuide: '#e8eaec',
		gitAdded: '#6cbf43',
		gitModified: '#478acc',
		gitDeleted: '#ff7383',
	},
	syntax: {
		comment: { fg: '#adaeb1', italic: true },
		keyword: { fg: '#fa8d3e' },
		string: { fg: '#86b300' },
		number: { fg: '#a37acc' },
		boolean: { fg: '#a37acc' },
		constant: { fg: '#a37acc' },
		function: { fg: '#f2ae49' },
		type: { fg: '#22a4e6' },
		variable: { fg: '#5c6166' },
		property: { fg: '#f07171' },
		tag: { fg: '#55b4d4' },
		operator: { fg: '#ed9366' },
		punctuation: { fg: '#5c6166' },
		label: { fg: '#e6b673' },
		escape: { fg: '#4cbf99' },
		embedded: { fg: '#5c6166' },
		error: { fg: '#e65050' },
		'markup.heading': { fg: '#86b300', bold: true },
		'markup.strong': { fg: '#f07171', bold: true },
		'markup.italic': { fg: '#f07171', italic: true },
		'markup.raw': { fg: '#ed9366' },
		'markup.link': { fg: '#22a4e6' },
		'markup.link.url': { fg: '#22a4e6', underline: true },
		'markup.list': { fg: '#f2ae49' },
		'markup.quote': { fg: '#4cbf99', italic: true },
	},
};
