import type { Theme } from './types';

/** Catppuccin Mocha. Palette from https://github.com/catppuccin/palette */
export const catppuccinMocha: Theme = {
	name: 'Catppuccin Mocha',
	ui: {
		bg: '#1e1e2e',
		panelBg: '#181825',
		barBg: '#11111b',
		statusBg: '#89b4fa',
		statusFg: '#11111b',
		text: '#cdd6f4',
		dim: '#a6adc8',
		faint: '#6c7086',
		accent: '#89b4fa',
		activeTabFg: '#cdd6f4',
		inactiveTabFg: '#6c7086',
		treeSelectedBg: '#313244',
		treeFocusBg: '#45475a',
		dirty: '#f9e2af',
		error: '#f38ba8',
		folder: '#cdd6f4',
		cursor: '#f5e0dc',
		scrollbar: '#585b70',
		gutter: '#6c7086',
		currentLine: '#181825',
		indentGuide: '#28293a',
		gitAdded: '#a6e3a1',
		gitModified: '#f9e2af',
		gitDeleted: '#f38ba8',
	},
	syntax: {
		comment: { fg: '#6c7086', italic: true },
		keyword: { fg: '#cba6f7' },
		string: { fg: '#a6e3a1' },
		number: { fg: '#fab387' },
		boolean: { fg: '#fab387' },
		constant: { fg: '#fab387' },
		function: { fg: '#89b4fa' },
		type: { fg: '#f9e2af' },
		variable: { fg: '#cdd6f4' },
		property: { fg: '#89b4fa' },
		tag: { fg: '#f38ba8' },
		operator: { fg: '#89dceb' },
		punctuation: { fg: '#9399b2' },
		label: { fg: '#f5c2e7' },
		escape: { fg: '#f5c2e7' },
		embedded: { fg: '#cdd6f4' },
		error: { fg: '#f38ba8' },
		'markup.heading': { fg: '#89b4fa', bold: true },
		'markup.strong': { fg: '#cdd6f4', bold: true },
		'markup.italic': { fg: '#cdd6f4', italic: true },
		'markup.raw': { fg: '#a6e3a1' },
		'markup.link': { fg: '#a6e3a1' },
		'markup.link.url': { fg: '#a6e3a1', underline: true },
		'markup.list': { fg: '#cba6f7' },
		'markup.quote': { fg: '#6c7086', italic: true },
	},
};
