import type { Theme } from './types';

/** Catppuccin Macchiato. Palette from https://github.com/catppuccin/palette */
export const catppuccinMacchiato: Theme = {
	name: 'Catppuccin Macchiato',
	ui: {
		bg: '#24273a',
		panelBg: '#1e2030',
		barBg: '#181926',
		statusBg: '#8aadf4',
		statusFg: '#181926',
		text: '#cad3f5',
		dim: '#a5adcb',
		faint: '#6e738d',
		accent: '#8aadf4',
		activeTabFg: '#cad3f5',
		inactiveTabFg: '#6e738d',
		treeSelectedBg: '#363a4f',
		treeFocusBg: '#494d64',
		dirty: '#eed49f',
		error: '#ed8796',
		folder: '#cad3f5',
		cursor: '#f4dbd6',
		scrollbar: '#5b6078',
		gutter: '#6e738d',
		currentLine: '#1e2030',
		indentGuide: '#2b2f42',
		gitAdded: '#a6da95',
		gitModified: '#eed49f',
		gitDeleted: '#ed8796',
	},
	syntax: {
		comment: { fg: '#6e738d', italic: true },
		keyword: { fg: '#c6a0f6' },
		string: { fg: '#a6da95' },
		number: { fg: '#f5a97f' },
		boolean: { fg: '#f5a97f' },
		constant: { fg: '#f5a97f' },
		function: { fg: '#8aadf4' },
		type: { fg: '#eed49f' },
		variable: { fg: '#cad3f5' },
		property: { fg: '#8aadf4' },
		tag: { fg: '#ed8796' },
		operator: { fg: '#91d7e3' },
		punctuation: { fg: '#939ab7' },
		label: { fg: '#f5bde6' },
		escape: { fg: '#f5bde6' },
		embedded: { fg: '#cad3f5' },
		error: { fg: '#ed8796' },
		'markup.heading': { fg: '#8aadf4', bold: true },
		'markup.strong': { fg: '#cad3f5', bold: true },
		'markup.italic': { fg: '#cad3f5', italic: true },
		'markup.raw': { fg: '#a6da95' },
		'markup.link': { fg: '#a6da95' },
		'markup.link.url': { fg: '#a6da95', underline: true },
		'markup.list': { fg: '#c6a0f6' },
		'markup.quote': { fg: '#6e738d', italic: true },
	},
};
