import type { Theme } from './types';

/** Catppuccin Latte. Palette from https://github.com/catppuccin/palette */
export const catppuccinLatte: Theme = {
	name: 'Catppuccin Latte',
	ui: {
		bg: '#eff1f5',
		panelBg: '#e6e9ef',
		barBg: '#dce0e8',
		statusBg: '#1e66f5',
		statusFg: '#eff1f5',
		text: '#4c4f69',
		dim: '#6c6f85',
		faint: '#9ca0b0',
		accent: '#1e66f5',
		activeTabFg: '#4c4f69',
		inactiveTabFg: '#8c8fa1',
		treeSelectedBg: '#ccd0da',
		treeFocusBg: '#bcc0cc',
		dirty: '#df8e1d',
		error: '#d20f39',
		folder: '#4c4f69',
		cursor: '#dc8a78',
		scrollbar: '#acb0be',
		gutter: '#9ca0b0',
		currentLine: '#e6e9ef',
		indentGuide: '#e5e7ed',
		gitAdded: '#40a02b',
		gitModified: '#df8e1d',
		gitDeleted: '#d20f39',
	},
	syntax: {
		comment: { fg: '#9ca0b0', italic: true },
		keyword: { fg: '#8839ef' },
		string: { fg: '#40a02b' },
		number: { fg: '#fe640b' },
		boolean: { fg: '#fe640b' },
		constant: { fg: '#fe640b' },
		function: { fg: '#1e66f5' },
		type: { fg: '#df8e1d' },
		variable: { fg: '#4c4f69' },
		property: { fg: '#1e66f5' },
		tag: { fg: '#d20f39' },
		operator: { fg: '#04a5e5' },
		punctuation: { fg: '#7c7f93' },
		label: { fg: '#ea76cb' },
		escape: { fg: '#ea76cb' },
		embedded: { fg: '#4c4f69' },
		error: { fg: '#d20f39' },
		'markup.heading': { fg: '#1e66f5', bold: true },
		'markup.strong': { fg: '#4c4f69', bold: true },
		'markup.italic': { fg: '#4c4f69', italic: true },
		'markup.raw': { fg: '#40a02b' },
		'markup.link': { fg: '#40a02b' },
		'markup.link.url': { fg: '#40a02b', underline: true },
		'markup.list': { fg: '#8839ef' },
		'markup.quote': { fg: '#9ca0b0', italic: true },
	},
};
