import type { Theme } from './types';

/**
 * Rosé Pine. Palette from https://github.com/rose-pine/neovim
 * (`lua/rose-pine/palette.lua`); the capture groups and UI slots follow the
 * official VS Code port, https://github.com/rose-pine/vscode.
 */
export const rosePine: Theme = {
	name: 'Rosé Pine',
	ui: {
		bg: '#191724',
		panelBg: '#1f1d2e',
		barBg: '#16141f',
		statusBg: '#c4a7e7',
		statusFg: '#191724',
		text: '#e0def4',
		dim: '#908caa',
		faint: '#6e6a86',
		accent: '#c4a7e7',
		activeTabFg: '#e0def4',
		inactiveTabFg: '#908caa',
		treeSelectedBg: '#403d52',
		treeFocusBg: '#26233a',
		dirty: '#f6c177',
		error: '#eb6f92',
		folder: '#e0def4',
		cursor: '#6e6a86',
		scrollbar: '#524f67',
		gutter: '#908caa',
		currentLine: '#21202e',
		indentGuide: '#221f2e',
		gitAdded: '#9ccfd8',
		gitModified: '#ebbcba',
		gitDeleted: '#eb6f92',
	},
	syntax: {
		comment: { fg: '#6e6a86', italic: true },
		keyword: { fg: '#31748f' },
		string: { fg: '#f6c177' },
		number: { fg: '#ebbcba' },
		boolean: { fg: '#ebbcba' },
		constant: { fg: '#ebbcba' },
		function: { fg: '#ebbcba' },
		type: { fg: '#9ccfd8' },
		variable: { fg: '#e0def4' },
		property: { fg: '#9ccfd8' },
		tag: { fg: '#9ccfd8' },
		operator: { fg: '#31748f' },
		punctuation: { fg: '#908caa' },
		label: { fg: '#c4a7e7' },
		escape: { fg: '#31748f' },
		embedded: { fg: '#e0def4' },
		error: { fg: '#eb6f92' },
		'markup.heading': { fg: '#c4a7e7', bold: true },
		'markup.strong': { fg: '#e0def4', bold: true },
		'markup.italic': { fg: '#e0def4', italic: true },
		'markup.raw': { fg: '#f6c177' },
		'markup.link': { fg: '#9ccfd8' },
		'markup.link.url': { fg: '#9ccfd8', underline: true },
		'markup.list': { fg: '#31748f' },
		'markup.quote': { fg: '#6e6a86', italic: true },
	},
};
