import type { Theme } from './types';

/**
 * Rosé Pine Moon. Palette from https://github.com/rose-pine/neovim
 * (`lua/rose-pine/palette.lua`); the capture groups and UI slots follow the
 * official VS Code port, https://github.com/rose-pine/vscode.
 */
export const rosePineMoon: Theme = {
	name: 'Rosé Pine Moon',
	ui: {
		bg: '#232136',
		panelBg: '#2a273f',
		barBg: '#1f1d30',
		statusBg: '#c4a7e7',
		statusFg: '#232136',
		text: '#e0def4',
		dim: '#908caa',
		faint: '#6e6a86',
		accent: '#c4a7e7',
		activeTabFg: '#e0def4',
		inactiveTabFg: '#908caa',
		treeSelectedBg: '#44415a',
		treeFocusBg: '#393552',
		dirty: '#f6c177',
		error: '#eb6f92',
		folder: '#e0def4',
		cursor: '#6e6a86',
		scrollbar: '#56526e',
		gutter: '#908caa',
		currentLine: '#2a283e',
		indentGuide: '#2b283e',
		gitAdded: '#9ccfd8',
		gitModified: '#ea9a97',
		gitDeleted: '#eb6f92',
	},
	syntax: {
		comment: { fg: '#6e6a86', italic: true },
		keyword: { fg: '#3e8fb0' },
		string: { fg: '#f6c177' },
		number: { fg: '#ea9a97' },
		boolean: { fg: '#ea9a97' },
		constant: { fg: '#ea9a97' },
		function: { fg: '#ea9a97' },
		type: { fg: '#9ccfd8' },
		variable: { fg: '#e0def4' },
		property: { fg: '#9ccfd8' },
		tag: { fg: '#9ccfd8' },
		operator: { fg: '#3e8fb0' },
		punctuation: { fg: '#908caa' },
		label: { fg: '#c4a7e7' },
		escape: { fg: '#3e8fb0' },
		embedded: { fg: '#e0def4' },
		error: { fg: '#eb6f92' },
		'markup.heading': { fg: '#c4a7e7', bold: true },
		'markup.strong': { fg: '#e0def4', bold: true },
		'markup.italic': { fg: '#e0def4', italic: true },
		'markup.raw': { fg: '#f6c177' },
		'markup.link': { fg: '#9ccfd8' },
		'markup.link.url': { fg: '#9ccfd8', underline: true },
		'markup.list': { fg: '#3e8fb0' },
		'markup.quote': { fg: '#6e6a86', italic: true },
	},
};
