import { createHash } from 'node:crypto';

/**
 * Writes the Homebrew formula for the current version to dist/release/dune.rb, with the
 * checksums of the archives `bun run release` produced. Copy it into the
 * dotbrains/homebrew-tap repository as Formula/dune.rb — the release workflow does that
 * for tagged builds.
 *
 * The formula installs the prebuilt binary; brew never compiles dune, so a machine that
 * installs it this way needs neither Bun nor Node.
 */
const RELEASE_DIR = './dist/release';

const { version, description, homepage, license } = await Bun.file('./package.json').json();

const ARCHIVES = {
	'darwin-arm64': 'dune-darwin-arm64.zip',
	'darwin-x64': 'dune-darwin-x64.zip',
	'linux-arm64': 'dune-linux-arm64.tar.gz',
	'linux-x64': 'dune-linux-x64.tar.gz',
} as const;

async function sha256(path: string): Promise<string> {
	const file = Bun.file(path);
	if (!(await file.exists())) {
		process.stderr.write(`missing archive: ${path} — run \`bun run release\` first\n`);
		process.exit(1);
	}
	return createHash('sha256')
		.update(new Uint8Array(await file.arrayBuffer()))
		.digest('hex');
}

const sums = Object.fromEntries(
	await Promise.all(
		Object.entries(ARCHIVES).map(async ([target, name]) => [
			target,
			await sha256(`${RELEASE_DIR}/${name}`),
		]),
	),
) as Record<keyof typeof ARCHIVES, string>;

const base = `${homepage}/releases/download/v${version}`;

const formula = `# Generated by scripts/formula.ts — do not edit by hand.
class Dune < Formula
  desc "${description.replace(/"/g, "'").split('—')[0]!.trim()}"
  homepage "${homepage}"
  version "${version}"
  license "${license}"

  on_macos do
    on_arm do
      url "${base}/${ARCHIVES['darwin-arm64']}"
      sha256 "${sums['darwin-arm64']}"
    end
    on_intel do
      url "${base}/${ARCHIVES['darwin-x64']}"
      sha256 "${sums['darwin-x64']}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/${ARCHIVES['linux-arm64']}"
      sha256 "${sums['linux-arm64']}"
    end
    on_intel do
      url "${base}/${ARCHIVES['linux-x64']}"
      sha256 "${sums['linux-x64']}"
    end
  end

  def install
    bin.install "dune"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dune --version")
  end
end
`;

await Bun.write(`${RELEASE_DIR}/dune.rb`, formula);
process.stdout.write(`wrote ${RELEASE_DIR}/dune.rb\n`);
