import { createHash } from 'node:crypto';
import { chmod, cp, mkdir, rm } from 'node:fs/promises';

/**
 * Writes the Homebrew formula for the current version to dist/release/dune.rb, with the
 * checksums of the archives `bun run release` produced, plus bottle tarballs built from
 * the matching dist/<target>/ binaries.
 *
 * The formula installs the prebuilt binary; brew never compiles dune, so a machine that
 * installs it this way needs neither Bun nor Node.
 */
const DIST_DIR = process.env.DUNE_DIST ?? './dist';
const RELEASE_DIR = `${DIST_DIR}/release`;
const BOTTLE_STAGE = `${DIST_DIR}/bottle`;

const { version, description, homepage, license } = await Bun.file('./package.json').json();

const ARCHIVES = {
	'darwin-arm64': 'dune-darwin-arm64.zip',
	'darwin-x64': 'dune-darwin-x64.zip',
	'linux-arm64': 'dune-linux-arm64.tar.gz',
	'linux-x64': 'dune-linux-x64.tar.gz',
} as const;

const BOTTLE_TAGS = {
	'darwin-arm64': 'arm64_ventura',
	'darwin-x64': 'ventura',
	'linux-arm64': 'arm64_linux',
	'linux-x64': 'x86_64_linux',
} as const;

type Target = keyof typeof ARCHIVES;

async function sha256(path: string): Promise<string> {
	const file = Bun.file(path);
	if (!(await file.exists())) {
		process.stderr.write(`missing archive: ${path} — run \`bun run release\` first\n`);
		process.exit(1);
	}
	return createHash('sha256')
		.update(new Uint8Array(await file.arrayBuffer()))
		.digest('hex');
}

const bottleName = (tag: string) => `dune-${version}.${tag}.bottle.tar.gz`;

async function bottle(target: Target, tag: string): Promise<string> {
	const binary = `${DIST_DIR}/${target}/dune`;
	if (!(await Bun.file(binary).exists())) {
		process.stderr.write(`missing binary: ${binary} — run \`bun run build ${target}\` first\n`);
		process.exit(1);
	}

	const stage = `${BOTTLE_STAGE}/${tag}`;
	await rm(stage, { recursive: true, force: true });
	await mkdir(`${stage}/dune/${version}/bin`, { recursive: true });
	await cp(binary, `${stage}/dune/${version}/bin/dune`);
	await chmod(`${stage}/dune/${version}/bin/dune`, 0o755);

	const path = `${RELEASE_DIR}/${bottleName(tag)}`;
	await Bun.$`tar -czf ${path} -C ${stage} dune`.env({
		...process.env,
		COPYFILE_DISABLE: '1',
	});
	return path;
}

const targets = Object.keys(ARCHIVES) as Target[];

const sums = Object.fromEntries(
	await Promise.all(
		targets.map(async (target) => [target, await sha256(`${RELEASE_DIR}/${ARCHIVES[target]}`)]),
	),
) as Record<Target, string>;

const bottles = Object.fromEntries(
	await Promise.all(
		targets.map(async (target) => [
			target,
			await sha256(await bottle(target, BOTTLE_TAGS[target])),
		]),
	),
) as Record<Target, string>;

await rm(BOTTLE_STAGE, { recursive: true, force: true });

const base = `${homepage}/releases/download/v${version}`;
const desc = description
	.replace(/"/g, "'")
	.split('—')[0]!
	.trim()
	.replace(/^(a|an|the) /i, '')
	.replace(/^./, (c: string) => c.toUpperCase());

const bottleSha256s = targets
	.map(
		(target) =>
			`    sha256 cellar: :any_skip_relocation, ${BOTTLE_TAGS[target]}: "${bottles[target]}"`,
	)
	.join('\n');

const formula = `# Generated by scripts/formula.ts — do not edit by hand.
class Dune < Formula
  desc "${desc}"
  homepage "${homepage}"
  version "${version}"
  license "${license}"

  on_macos do
    on_arm do
      url "${base}/${ARCHIVES['darwin-arm64']}"
      sha256 "${sums['darwin-arm64']}"
    end
    on_intel do
      url "${base}/${ARCHIVES['darwin-x64']}"
      sha256 "${sums['darwin-x64']}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/${ARCHIVES['linux-arm64']}"
      sha256 "${sums['linux-arm64']}"
    end
    on_intel do
      url "${base}/${ARCHIVES['linux-x64']}"
      sha256 "${sums['linux-x64']}"
    end
  end

  bottle do
    root_url "${base}"
${bottleSha256s}
  end

  def install
    bin.install "dune"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dune --version")
  end
end
`;

await Bun.write(`${RELEASE_DIR}/dune.rb`, formula);
process.stdout.write(`wrote ${RELEASE_DIR}/dune.rb\n`);
